# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:

networks:
  byfn:
services:

  orderer0.example.com:
    extends:
      file:   base/docker-compose-base.yml
      service: orderer0.example.com
    container_name: orderer0.example.com
    networks:
      - byfn

  orderer1.example.com:
    extends:
      file:   base/docker-compose-base.yml
      service: orderer1.example.com
    container_name: orderer1.example.com
    networks:
      - byfn

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base.yml
      service: peer0.org1.example.com
    networks:
      - byfn

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:  base/docker-compose-base.yml
      service: peer1.org1.example.com
    networks:
      - byfn