# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.example.com:
    container_name: orderer0.example.com
    extends:
      file: orderer-base.yml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/etc/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls:/etc/hyperledger/orderer/tls
    ports:
      - 7050:7050

  orderer1.example.com:
    container_name: orderer1.example.com
    extends:
      file: orderer-base.yml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/etc/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls:/etc/hyperledger/orderer/tls
    ports:
      - 8050:7050

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: peer-base.yml
      service: peer-base
    environment:
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=org1.example.com
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/msp/users/Admin@org1.example.com/tls/ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/msp/users/Admin@org1.example.com/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/msp/users/Admin@org1.example.com/tls/client.key
    volumes:
        - /var/run/:/host/var/run/
        - ../channel-artifacts:/etc/hyperledger/configtx
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/fabric/msp/users
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem:/etc/hyperledger/fabric/tlsca.example.com-cert.pem
        - peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file: peer-base.yml
      service: peer-base
    environment:
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org1.example.com:7052
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=org1.example.com
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/fabric/msp/users/Admin@org1.example.com/tls/ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/fabric/msp/users/Admin@org1.example.com/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/fabric/msp/users/Admin@org1.example.com/tls/client.key
    volumes:
        - /var/run/:/host/var/run/
        - ../channel-artifacts:/etc/hyperledger/configtx
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - ../crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/fabric/msp/users
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem:/etc/hyperledger/fabric/tlsca.example.com-cert.pem
        - peer1.org1.example.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  zookeeper0.example.com:
    container_name: zookeeper0.example.com
    extends:
      file: kafka-base.yml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    # ports:
    #   - 2181:2181
    #   - 2888:2888
    #   - 3888:3888

  zookeeper1.example.com:
    container_name: zookeeper1.example.com
    extends:
      file: kafka-base.yml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    # ports:
    #   - 2181:2181
    #   - 2888:2888
    #   - 3888:3888

  zookeeper2.example.com:
    container_name: zookeeper2.example.com
    extends:
      file: kafka-base.yml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    # ports:
    #   - 2181:2181
    #   - 2888:2888
    #   - 3888:3888

  kafka0.example.com:
    container_name: kafka0.example.com
    extends:
      file: kafka-base.yml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    ports:
      - 9092:9092
      - 9093:9093

  kafka1.example.com:
    container_name: kafka1.example.com
    extends:
      file: kafka-base.yml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    ports:
      - 10092:9092
      - 10093:9093

  kafka2.example.com:
    container_name: kafka2.example.com
    extends:
      file: kafka-base.yml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    ports:
      - 11092:9092
      - 11093:9093

  kafka3.example.com:
    container_name: kafka3.example.com
    extends:
      file: kafka-base.yml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    ports:
      - 12092:9092
      - 12093:9093
      